#!/usr/bin/env python
# -*- coding: utf-8 -*-

#  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
#
#  md2rst
#  Copyright 2016 Christopher Simpkins
#  Source: https://github.com/chrissimpkins/md2rst
#  MIT license
#
#  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

import sys
import os
import subprocess

VERSION = "v0.9.0"

#  Modified from http://stackoverflow.com/questions/377017/test-if-executable-exists-in-python
def which(program):
    """Test for the existence of an executable by defined executable path or on the system PATH"""
    fpath, fname = os.path.split(program)
    if fpath:
        if os.path.isfile(program) and os.access(program, os.X_OK):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            path = path.strip('"')
            exe_file = os.path.join(path, program)
            if os.path.isfile(exe_file) and os.access(exe_file, os.X_OK):
                return exe_file
    return None

def execute(command):
    """Execute a system command with the Python subprocess module"""
    try:
        response = subprocess.call(command, shell=True)
        if response == 0:
            return True
        else:
            return False
    except subprocess.CalledProcessError as cpe:
        sys.stderr.write("[md2rst] Error: There was an error with the execution of Pandoc. " + str(cpe.output))
        sys.exit(1)

def convert(mdpath, rstpath):
    """Convert a Markdown file to a reStructuredText file with the Pandoc executable"""
    command = "pandoc --from=markdown --to=rst --output=" + rstpath + " " + mdpath
    return execute(command)  # returns True or False based upon success of execution


def main(args):
    if which("pandoc") is not None:   # test for pandoc install on system
        mdpath = ""
        rstpath = ""

        if len(args) == 2:
            pathone = args[0]
            pathtwo = args[1]

            if pathone.lower().endswith(".md"):
                mdpath = pathone
                rstpath = pathtwo
            elif pathtwo.lower().endswith(".md"):
                mdpath = pathtwo
                rstpath = pathone
            elif pathone.lower() == "readme":
                mdpath = pathone
                rstpath = pathtwo
            elif pathtwo.lower() == "readme":
                mdpath = pathtwo
                rstpath = pathone
            else:
                sys.stderr.write("[md2rst] Error: Unable to detect the Markdown file in your command.  Please use a Markdown file path that has a .md extension or uses the non-case sensitive file name README.")
                sys.exit(1)

            if convert(mdpath, rstpath) is True:
                response_string = "[md2rst] '" + mdpath + "' was converted to '" + rstpath + "'."
                print(response_string)
                sys.exit(0)
            else:
                sys.stderr.write("[md2rst] Error: There was an error with the Pandoc conversion")
                sys.exit(1)
        elif len(args) == 1:
            mdpath = args[0]
            if "." in mdpath:
                rstpath_dir = os.path.split(mdpath)[0]
                rstpath_basename = os.path.basename(mdpath)
                rstpath_pre = rstpath_basename.split(".")[0]
                rstpath_base = rstpath_pre + ".rst"
                rstpath = os.path.join(rstpath_dir, rstpath_base)
            else:
                rstpath = mdpath + ".rst"

            if convert(mdpath, rstpath) is True:
                response_string = "[md2rst] '" + mdpath + "' was converted to '" + rstpath + "'."
                print(response_string)
                sys.exit(0)
            else:
                sys.stderr.write("[md2rst] Error: There was an error with the Pandoc conversion")
                sys.exit(1)

    else:
        sys.stderr.write("[md2rst] Error: Pandoc was not found on your system.  Please install Pandoc and then try again.\n")
        sys.exit(1)


if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.stderr.write("[md2rst] Error: Please include at least one filepath argument in your command.\n")
        sys.exit(1)
    elif sys.argv[1] == "-u" or sys.argv[1] == "--usage":
        print("$ md2rst [Markdown file path] <rst file path>")
        sys.exit(0)
    elif sys.argv[1] == "-h" or sys.argv[1] == "--help":
        help_string = """
--------------------------------------------------
  md2rst
  Copyright 2016 Christopher Simpkins
  Source: https://github.com/chrissimpkins/md2rst
  MIT license
--------------------------------------------------

ABOUT

  md2rst is a Python script that converts Markdown syntax files to reStructuredText syntax files with Pandoc.  A Pandoc install on your system is mandatory in order to use the script.

USAGE

  $ md2rst [Markdown file path] <rst file path>

  The rst file path is optional.  The default write occurs in the same directory as the Markdown file and uses the same file name.
"""
        print(help_string)
    elif sys.argv[1] == "-v" or sys.argv[1] == "--version":
        print("md2rst " + VERSION)
    else:
        main(sys.argv[1:])
